/* Body file for function Sensor
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "sensor.h"
//#include <stdio.h>


void sensor_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[Sensor] Startup");
}

void sensor_PI_sensorControl
      (const asn1SccSensorControl_Data *IN_sensorcontroldata)

{
   // Write your code here
}


void sensor_PI_tick(void)
{
   // Write your code here
}


