/* Body file for function f1
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "f1.h"
#include <stdio.h>

static asn1SccMyInteger myStaticInt = 0;

void f1_startup(void)
{
}

void f1_PI_response
      (const asn1SccMyInteger *IN_p1)

{
  printf("Pong: %d\n", (int)*IN_p1);
  myStaticInt = (int)*IN_p1;
}

void f1_PI_trigger(void)
{
  if (myStaticInt <= 5) {
    printf("Sending ping: %d\n", (int)myStaticInt);
    f1_RI_query(&myStaticInt);
  }
}

