/* Body file for function Assembler
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "assembler.h"
//#include <stdio.h>


void assembler_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[Assembler] Startup");
}

void assembler_PI_Deliver
      (const asn1SccDeliveredRequestData *IN_deliverreqseq)

{
   // Write your code here
}


void assembler_PI_Init
      (const asn1SccInitRequestData *IN_initreqseq)

{
   // Write your code here
}


void assembler_PI_UartHwas_ReadByteAsyncCmd_Ri
      (const asn1SccUartHwasInterfaceType_ReadByteAsyncCmd_TypeNotify *IN_inputparam)

{
   // Write your code here
}


