all:
	mkdir -p code
	cd code && opengeode --toAda ../*.pr
	asn1scc -fp AUTO -typePrefix asn1Scc -o code -equal -Ada dataview-uniq.asn code/modemanager_datamodel.asn
	cd code && gnat make modemanager
clean:
	rm -rf code