/* Message identifiers for the GUI messages
 * Used by the code of the GUIs and by the ctypes Python interface
 * DO NOT EDIT THIS FILE MANUALLY - MODIFY THE KAZOO TEMPLATE IF NECESSARY
*/
#pragma once

// 2 poll, tm
typedef enum {
   i_tm
} T_mcgui_PI_list;

typedef enum {
   i_tc
} T_mcgui_RI_list;

