/* Header file for function MCGUI
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void mcgui_startup(void);

/* Provided interfaces */
void mcgui_PI_Poll( void );


void mcgui_PI_tm( const asn1SccTM_Data * );

/* Required interfaces */
extern void mcgui_RI_tc( const asn1SccTC_Data * );


#ifdef __cplusplus
}
#endif

