/* Body file for function Datapool
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "datapool.h"
//#include <stdio.h>


void datapool_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[Datapool] Startup");
}

void datapool_PI_ActuatorStatusUpdate
      (const asn1SccActuatorStatusUpdate_Data *IN_actuatorstatusupdate)

{
   // Write your code here
}


void datapool_PI_SensorStatusUpdate
      (const asn1SccSensorStatusUpdate_Data *IN_sensorstatusupdate)

{
   // Write your code here
}


void datapool_PI_SystemDataRequest
      (asn1SccSystemDataRequest_Data *OUT_systemdatarequest)

{
   // Write your code here
}


