/* Body file for function Datapool
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "datapool.h"
#include <stdio.h>

asn1SccActuatorStatusUpdate_Data actuatorStatus;
asn1SccSensorStatusUpdate_Data sensorStatus;


void datapool_startup(void)
{

}

void datapool_PI_ActuatorStatusUpdate
      (const asn1SccActuatorStatusUpdate_Data *IN_actuatorstatusupdate)

{
   actuatorStatus.device_state = IN_actuatorstatusupdate->device_state;
   actuatorStatus.acceleration = IN_actuatorstatusupdate->acceleration;
}


void datapool_PI_SensorStatusUpdate
      (const asn1SccSensorStatusUpdate_Data *IN_sensorstatusupdate)

{
   sensorStatus.device_state = IN_sensorstatusupdate->device_state;
   sensorStatus.system_phisic_attrs.velocity = IN_sensorstatusupdate->system_phisic_attrs.velocity;
   sensorStatus.system_phisic_attrs.height = IN_sensorstatusupdate->system_phisic_attrs.height;
}


void datapool_PI_SystemDataRequest
      (asn1SccSystemDataRequest_Data *OUT_systemdatarequest)

{
   OUT_systemdatarequest->actuator_state = actuatorStatus.device_state;
   OUT_systemdatarequest->sensor_state = sensorStatus.device_state;
   OUT_systemdatarequest->acceleration = actuatorStatus.acceleration;
   OUT_systemdatarequest->system_phisic_attrs.velocity = sensorStatus.system_phisic_attrs.velocity;
   OUT_systemdatarequest->system_phisic_attrs.height = sensorStatus.system_phisic_attrs.height;
}


