/* Body file for function PhysicSimulation
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "physicsimulation.h"
//#include <stdio.h>


void physicsimulation_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[PhysicSimulation] Startup");
}

void physicsimulation_PI_actuate(void)
{
   // Write your code here
}


void physicsimulation_PI_sense( asn1SccSense_Data * OUT_sensedata)
{
   // Write your code here
}

void physicsimulation_PI_tick(void)
{
   // Write your code here
}


