/* Body file for function PhysicSimulation
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "physicsimulation.h"

#define GRAVITY_ACCELERATION -0.05

static int phisicTick;
static asn1SccSystemPhisicAttrs systemPhisicAttrs;
static asn1Real acceleration;

void physicsimulation_startup(void)
{
   phisicTick = 0;
   systemPhisicAttrs.height = 0.0;
   systemPhisicAttrs.velocity = 0.0;
   acceleration = 0.0;
}

void physicsimulation_PI_actuate(const asn1SccPhisicValType * IN_acceleration)
{
   acceleration = *IN_acceleration;
}


void physicsimulation_PI_sense( asn1SccSense_Data * OUT_sensedata)
{
   OUT_sensedata->phisic_tick = phisicTick;
   OUT_sensedata->system_phisic_attrs.height = systemPhisicAttrs.height;
   OUT_sensedata->system_phisic_attrs.velocity = systemPhisicAttrs.velocity;
   OUT_sensedata->acceleration = acceleration;
}

void physicsimulation_PI_tick(void)
{
   systemPhisicAttrs.height = systemPhisicAttrs.height + systemPhisicAttrs.velocity;
   systemPhisicAttrs.velocity = systemPhisicAttrs.velocity + acceleration + GRAVITY_ACCELERATION;

   phisicTick++;
}


