/* Body file for function Driver
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "driver.h"
#include "linux_serial_ccsds.h"

void driver_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[Driver] Startup");
}

void driver_PI_Deliver
      (const asn1SccDeliveredRequestData *IN_p1)
{
   void* private_data = (void *) IN_p1->private_data;
   uint8_t *data = (uint8_t *) IN_p1->message_data;
   size_t length = IN_p1->length;
   LinuxSerialCcsdsSend(private_data, data, length);
}

void driver_PI_Init
      (const asn1SccInitRequestData *IN_initreqseq)
{
   void *private_data = (void *) IN_initreqseq->private_data;
   enum SystemBus bus_id = (enum SystemBus) IN_initreqseq->bus_id;
   enum SystemDevice device_id = (enum SystemDevice) IN_initreqseq->device_id;
   asn1SccRS485_LINUX_Conf_T *device_configuration = (asn1SccRS485_LINUX_Conf_T *) IN_initreqseq->device_configuration;
   asn1SccRS485_LINUX_Conf_T *remote_device_configuration = (asn1SccRS485_LINUX_Conf_T *) IN_initreqseq->remote_device_configuration;
   LinuxSerialCcsdsInit(private_data, bus_id, device_id, device_configuration, remote_device_configuration);
}
