/* Header file for function ScienceGUI
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void sciencegui_startup(void);

/* Provided interfaces */
void sciencegui_PI_dataStream( const asn1SccDataStream_Data * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif

