/* Body file for function Actuator
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "actuator.h"
//#include <stdio.h>


void actuator_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[Actuator] Startup");
}

void actuator_PI_actuatorControl
      (const asn1SccActuatorControl_Data *IN_actuatorcontroldata)

{
   // Write your code here
}


void actuator_PI_tick(void)
{
   // Write your code here
}


